export type Property = "alignContent" |
	"alignItems" |
	"alignSelf" |
	"alignmentBaseline" |
	"animation" |
	"animationDelay" |
	"animationDirection" |
	"animationDuration" |
	"animationFillMode" |
	"animationIterationCount" |
	"animationName" |
	"animationPlayState" |
	"animationTimingFunction" |
	"backfaceVisibility" |
	"background" |
	"backgroundAttachment" |
	"backgroundClip" |
	"backgroundColor" |
	"backgroundImage" |
	"backgroundOrigin" |
	"backgroundPosition" |
	"backgroundPositionX" |
	"backgroundPositionY" |
	"backgroundRepeat" |
	"backgroundSize" |
	"baselineShift" |
	"border" |
	"borderBottom" |
	"borderBottomColor" |
	"borderBottomLeftRadius" |
	"borderBottomRightRadius" |
	"borderBottomStyle" |
	"borderBottomWidth" |
	"borderCollapse" |
	"borderColor" |
	"borderImage" |
	"borderImageOutset" |
	"borderImageRepeat" |
	"borderImageSlice" |
	"borderImageSource" |
	"borderImageWidth" |
	"borderLeft" |
	"borderLeftColor" |
	"borderLeftStyle" |
	"borderLeftWidth" |
	"borderRadius" |
	"borderRight" |
	"borderRightColor" |
	"borderRightStyle" |
	"borderRightWidth" |
	"borderSpacing" |
	"borderStyle" |
	"borderTop" |
	"borderTopColor" |
	"borderTopLeftRadius" |
	"borderTopRightRadius" |
	"borderTopStyle" |
	"borderTopWidth" |
	"borderWidth" |
	"bottom" |
	"boxShadow" |
	"boxSizing" |
	"breakAfter" |
	"breakBefore" |
	"breakInside" |
	"captionSide" |
	"clear" |
	"clip" |
	"clipPath" |
	"clipRule" |
	"color" |
	"colorInterpolationFilters" |
	"columnCount" |
	"columnFill" |
	"columnGap" |
	"columnRule" |
	"columnRuleColor" |
	"columnRuleStyle" |
	"columnRuleWidth" |
	"columnSpan" |
	"columnWidth" |
	"columns" |
	"content" |
	"counterIncrement" |
	"counterReset" |
	"cssFloat" |
	"cssText" |
	"cursor" |
	"direction" |
	"display" |
	"dominantBaseline" |
	"emptyCells" |
	"enableBackground" |
	"fill" |
	"fillOpacity" |
	"fillRule" |
	"filter" |
	"flex" |
	"flexBasis" |
	"flexDirection" |
	"flexFlow" |
	"flexGrow" |
	"flexShrink" |
	"flexWrap" |
	"floodColor" |
	"floodOpacity" |
	"font" |
	"fontFamily" |
	"fontFeatureSettings" |
	"fontSize" |
	"fontSizeAdjust" |
	"fontStretch" |
	"fontStyle" |
	"fontVariant" |
	"fontWeight" |
	"glyphOrientationHorizontal" |
	"glyphOrientationVertical" |
	"height" |
	"imeMode" |
	"justifyContent" |
	"kerning" |
	"layoutGrid" |
	"layoutGridChar" |
	"layoutGridLine" |
	"layoutGridMode" |
	"layoutGridType" |
	"left" |
	"readonly" |
	"letterSpacing" |
	"lightingColor" |
	"lineBreak" |
	"lineHeight" |
	"listStyle" |
	"listStyleImage" |
	"listStylePosition" |
	"listStyleType" |
	"margin" |
	"marginBottom" |
	"marginLeft" |
	"marginRight" |
	"marginTop" |
	"marker" |
	"markerEnd" |
	"markerMid" |
	"markerStart" |
	"mask" |
	"maxHeight" |
	"maxWidth" |
	"minHeight" |
	"minWidth" |
	"msContentZoomChaining" |
	"msContentZoomLimit" |
	"msContentZoomLimitMax" |
	"msContentZoomLimitMin" |
	"msContentZoomSnap" |
	"msContentZoomSnapPoints" |
	"msContentZoomSnapType" |
	"msContentZooming" |
	"msFlowFrom" |
	"msFlowInto" |
	"msFontFeatureSettings" |
	"msGridColumn" |
	"msGridColumnAlign" |
	"msGridColumnSpan" |
	"msGridColumns" |
	"msGridRow" |
	"msGridRowAlign" |
	"msGridRowSpan" |
	"msGridRows" |
	"msHighContrastAdjust" |
	"msHyphenateLimitChars" |
	"msHyphenateLimitLines" |
	"msHyphenateLimitZone" |
	"msHyphens" |
	"msImeAlign" |
	"msOverflowStyle" |
	"msScrollChaining" |
	"msScrollLimit" |
	"msScrollLimitXMax" |
	"msScrollLimitXMin" |
	"msScrollLimitYMax" |
	"msScrollLimitYMin" |
	"msScrollRails" |
	"msScrollSnapPointsX" |
	"msScrollSnapPointsY" |
	"msScrollSnapType" |
	"msScrollSnapX" |
	"msScrollSnapY" |
	"msScrollTranslation" |
	"msTextCombineHorizontal" |
	"msTextSizeAdjust" |
	"msTouchAction" |
	"msTouchSelect" |
	"msUserSelect" |
	"msWrapFlow" |
	"msWrapMargin" |
	"msWrapThrough" |
	"opacity" |
	"order" |
	"orphans" |
	"outline" |
	"outlineColor" |
	"outlineOffset" |
	"outlineStyle" |
	"outlineWidth" |
	"overflow" |
	"overflowX" |
	"overflowY" |
	"padding" |
	"paddingBottom" |
	"paddingLeft" |
	"paddingRight" |
	"paddingTop" |
	"pageBreakAfter" |
	"pageBreakBefore" |
	"pageBreakInside" |
	"perspective" |
	"perspectiveOrigin" |
	"pointerEvents" |
	"position" |
	"quotes" |
	"right" |
	"rotate" |
	"rubyAlign" |
	"rubyOverhang" |
	"rubyPosition" |
	"scale" |
	"stopColor" |
	"stopOpacity" |
	"stroke" |
	"strokeDasharray" |
	"strokeDashoffset" |
	"strokeLinecap" |
	"strokeLinejoin" |
	"strokeMiterlimit" |
	"strokeOpacity" |
	"strokeWidth" |
	"tableLayout" |
	"textAlign" |
	"textAlignLast" |
	"textAnchor" |
	"textDecoration" |
	"textIndent" |
	"textJustify" |
	"textKashida" |
	"textKashidaSpace" |
	"textOverflow" |
	"textShadow" |
	"textTransform" |
	"textUnderlinePosition" |
	"top" |
	"touchAction" |
	"transform" |
	"transformOrigin" |
	"transformStyle" |
	"transition" |
	"transitionDelay" |
	"transitionDuration" |
	"transitionProperty" |
	"transitionTimingFunction" |
	"translate" |
	"unicodeBidi" |
	"verticalAlign" |
	"visibility" |
	"WebkitAlignContent" |
	"WebkitAlignItems" |
	"WebkitAlignSelf" |
	"WebkitAnimation" |
	"WebkitAnimationDelay" |
	"WebkitAnimationDirection" |
	"WebkitAnimationDuration" |
	"WebkitAnimationFillMode" |
	"WebkitAnimationIterationCount" |
	"WebkitAnimationName" |
	"WebkitAnimationPlayState" |
	"WebkitAnimationTimingFunction" |
	"WebkitAppearance" |
	"WebkitBackfaceVisibility" |
	"WebkitBackgroundClip" |
	"WebkitBackgroundOrigin" |
	"WebkitBackgroundSize" |
	"WebkitBorderBottomLeftRadius" |
	"WebkitBorderBottomRightRadius" |
	"WebkitBorderImage" |
	"WebkitBorderRadius" |
	"WebkitBorderTopLeftRadius" |
	"WebkitBorderTopRightRadius" |
	"WebkitBoxAlign" |
	"WebkitBoxDirection" |
	"WebkitBoxFlex" |
	"WebkitBoxOrdinalGroup" |
	"WebkitBoxOrient" |
	"WebkitBoxPack" |
	"WebkitBoxSizing" |
	"WebkitColumnBreakAfter" |
	"WebkitColumnBreakBefore" |
	"WebkitColumnBreakInside" |
	"WebkitColumnCount" |
	"WebkitColumnGap" |
	"WebkitColumnRule" |
	"WebkitColumnRuleColor" |
	"WebkitColumnRuleStyle" |
	"WebkitColumnRuleWidth" |
	"WebkitColumnSpan" |
	"WebkitColumnWidth" |
	"WebkitColumns" |
	"WebkitFilter" |
	"WebkitFlex" |
	"WebkitFlexBasis" |
	"WebkitFlexDirection" |
	"WebkitFlexFlow" |
	"WebkitFlexGrow" |
	"WebkitFlexShrink" |
	"WebkitFlexWrap" |
	"WebkitJustifyContent" |
	"WebkitOrder" |
	"WebkitPerspective" |
	"WebkitPerspectiveOrigin" |
	"WebkitTapHighlightColor" |
	"WebkitTextFillColor" |
	"WebkitTextSizeAdjust" |
	"WebkitTextStroke" |
	"WebkitTextStrokeColor" |
	"WebkitTextStrokeWidth" |
	"WebkitTransform" |
	"WebkitTransformOrigin" |
	"WebkitTransformStyle" |
	"WebkitTransition" |
	"WebkitTransitionDelay" |
	"WebkitTransitionDuration" |
	"WebkitTransitionProperty" |
	"WebkitTransitionTimingFunction" |
	"WebkitUserModify" |
	"WebkitUserSelect" |
	"WebkitWritingMode" |
	"whiteSpace" |
	"widows" |
	"width" |
	"wordBreak" |
	"wordSpacing" |
	"wordWrap" |
	"writingMode" |
	"zIndex" |
	"zoom" |
	"resize" |
	"userSelect";

export type HyphenatedProperty = "align-content" |
	"align-items" |
	"align-self" |
	"alignment-baseline" |
	"animation" |
	"animation-delay" |
	"animation-direction" |
	"animation-duration" |
	"animation-fill-mode" |
	"animation-iteration-count" |
	"animation-name" |
	"animation-play-state" |
	"animation-timing-function" |
	"backface-visibility" |
	"background" |
	"background-attachment" |
	"background-clip" |
	"background-color" |
	"background-image" |
	"background-origin" |
	"background-position" |
	"background-position-x" |
	"background-position-y" |
	"background-repeat" |
	"background-size" |
	"baseline-shift" |
	"border" |
	"border-bottom" |
	"border-bottom-color" |
	"border-bottom-left-radius" |
	"border-bottom-right-radius" |
	"border-bottom-style" |
	"border-bottom-width" |
	"border-collapse" |
	"border-color" |
	"border-image" |
	"border-image-outset" |
	"border-image-repeat" |
	"border-image-slice" |
	"border-image-source" |
	"border-image-width" |
	"border-left" |
	"border-left-color" |
	"border-left-style" |
	"border-left-width" |
	"border-radius" |
	"border-right" |
	"border-right-color" |
	"border-right-style" |
	"border-right-width" |
	"border-spacing" |
	"border-style" |
	"border-top" |
	"border-top-color" |
	"border-top-left-radius" |
	"border-top-right-radius" |
	"border-top-style" |
	"border-top-width" |
	"border-width" |
	"bottom" |
	"box-shadow" |
	"box-sizing" |
	"break-after" |
	"break-before" |
	"break-inside" |
	"caption-side" |
	"clear" |
	"clip" |
	"clip-path" |
	"clip-rule" |
	"color" |
	"color-interpolation-filters" |
	"column-count" |
	"column-fill" |
	"column-gap" |
	"column-rule" |
	"column-rule-color" |
	"column-rule-style" |
	"column-rule-width" |
	"column-span" |
	"column-width" |
	"columns" |
	"content" |
	"counter-increment" |
	"counter-reset" |
	"css-float" |
	"css-text" |
	"cursor" |
	"direction" |
	"display" |
	"dominant-baseline" |
	"empty-cells" |
	"enable-background" |
	"fill" |
	"fill-opacity" |
	"fill-rule" |
	"filter" |
	"flex" |
	"flex-basis" |
	"flex-direction" |
	"flex-flow" |
	"flex-grow" |
	"flex-shrink" |
	"flex-wrap" |
	"flood-color" |
	"flood-opacity" |
	"font" |
	"font-family" |
	"font-feature-settings" |
	"font-size" |
	"font-size-adjust" |
	"font-stretch" |
	"font-style" |
	"font-variant" |
	"font-weight" |
	"glyph-orientation-horizontal" |
	"glyph-orientation-vertical" |
	"height" |
	"ime-mode" |
	"justify-content" |
	"kerning" |
	"layout-grid" |
	"layout-grid-char" |
	"layout-grid-line" |
	"layout-grid-mode" |
	"layout-grid-type" |
	"left" |
	"readonly" |
	"letter-spacing" |
	"lighting-color" |
	"line-break" |
	"line-height" |
	"list-style" |
	"list-style-image" |
	"list-style-position" |
	"list-style-type" |
	"margin" |
	"margin-bottom" |
	"margin-left" |
	"margin-right" |
	"margin-top" |
	"marker" |
	"marker-end" |
	"marker-mid" |
	"marker-start" |
	"mask" |
	"max-height" |
	"max-width" |
	"min-height" |
	"min-width" |
	"-ms-content-zoom-chaining" |
	"-ms-content-zoom-limit" |
	"-ms-content-zoom-limit-max" |
	"-ms-content-zoom-limit-min" |
	"-ms-content-zoom-snap" |
	"-ms-content-zoom-snap-points" |
	"-ms-content-zoom-snap-type" |
	"-ms-content-zooming" |
	"-ms-flow-from" |
	"-ms-flow-into" |
	"-ms-font-feature-settings" |
	"-ms-grid-column" |
	"-ms-grid-column-align" |
	"-ms-grid-column-span" |
	"-ms-grid-columns" |
	"-ms-grid-row" |
	"-ms-grid-row-align" |
	"-ms-grid-row-span" |
	"-ms-grid-rows" |
	"-ms-high-contrast-adjust" |
	"-ms-hyphenate-limit-chars" |
	"-ms-hyphenate-limit-lines" |
	"-ms-hyphenate-limit-zone" |
	"-ms-hyphens" |
	"-ms-ime-align" |
	"-ms-overflow-style" |
	"-ms-scroll-chaining" |
	"-ms-scroll-limit" |
	"-ms-scroll-limit-x-max" |
	"-ms-scroll-limit-x-min" |
	"-ms-scroll-limit-y-max" |
	"-ms-scroll-limit-y-min" |
	"-ms-scroll-rails" |
	"-ms-scroll-snap-points-x" |
	"-ms-scroll-snap-points-y" |
	"-ms-scroll-snap-type" |
	"-ms-scroll-snap-x" |
	"-ms-scroll-snap-y" |
	"-ms-scroll-translation" |
	"-ms-text-combine-horizontal" |
	"-ms-text-size-adjust" |
	"-ms-touch-action" |
	"-ms-touch-select" |
	"-ms-user-select" |
	"-ms-wrap-flow" |
	"-ms-wrap-margin" |
	"-ms-wrap-through" |
	"opacity" |
	"order" |
	"orphans" |
	"outline" |
	"outline-color" |
	"outline-offset" |
	"outline-style" |
	"outline-width" |
	"overflow" |
	"overflow-x" |
	"overflow-y" |
	"padding" |
	"padding-bottom" |
	"padding-left" |
	"padding-right" |
	"padding-top" |
	"page-break-after" |
	"page-break-before" |
	"page-break-inside" |
	"perspective" |
	"perspective-origin" |
	"pointer-events" |
	"position" |
	"quotes" |
	"right" |
	"rotate" |
	"ruby-align" |
	"ruby-overhang" |
	"ruby-position" |
	"scale" |
	"stop-color" |
	"stop-opacity" |
	"stroke" |
	"stroke-dasharray" |
	"stroke-dashoffset" |
	"stroke-linecap" |
	"stroke-linejoin" |
	"stroke-miterlimit" |
	"stroke-opacity" |
	"stroke-width" |
	"table-layout" |
	"text-align" |
	"text-align-last" |
	"text-anchor" |
	"text-decoration" |
	"text-indent" |
	"text-justify" |
	"text-kashida" |
	"text-kashida-space" |
	"text-overflow" |
	"text-shadow" |
	"text-transform" |
	"text-underline-position" |
	"top" |
	"touch-action" |
	"transform" |
	"transform-origin" |
	"transform-style" |
	"transition" |
	"transition-delay" |
	"transition-duration" |
	"transition-property" |
	"transition-timing-function" |
	"translate" |
	"unicode-bidi" |
	"vertical-align" |
	"visibility" |
	"-webkit-align-content" |
	"-webkit-align-items" |
	"-webkit-align-self" |
	"-webkit-animation" |
	"-webkit-animation-delay" |
	"-webkit-animation-direction" |
	"-webkit-animation-duration" |
	"-webkit-animation-fill-mode" |
	"-webkit-animation-iteration-count" |
	"-webkit-animation-name" |
	"-webkit-animation-play-state" |
	"-webkit-animation-timing-function" |
	"-webkit-appearance" |
	"-webkit-backface-visibility" |
	"-webkit-background-clip" |
	"-webkit-background-origin" |
	"-webkit-background-size" |
	"-webkit-border-bottom-left-radius" |
	"-webkit-border-bottom-right-radius" |
	"-webkit-border-image" |
	"-webkit-border-radius" |
	"-webkit-border-top-left-radius" |
	"-webkit-border-top-right-radius" |
	"-webkit-box-align" |
	"-webkit-box-direction" |
	"-webkit-box-flex" |
	"-webkit-box-ordinal-group" |
	"-webkit-box-orient" |
	"-webkit-box-pack" |
	"-webkit-box-sizing" |
	"-webkit-column-break-after" |
	"-webkit-column-break-before" |
	"-webkit-column-break-inside" |
	"-webkit-column-count" |
	"-webkit-column-gap" |
	"-webkit-column-rule" |
	"-webkit-column-rule-color" |
	"-webkit-column-rule-style" |
	"-webkit-column-rule-width" |
	"-webkit-column-span" |
	"-webkit-column-width" |
	"-webkit-columns" |
	"-webkit-filter" |
	"-webkit-flex" |
	"-webkit-flex-basis" |
	"-webkit-flex-direction" |
	"-webkit-flex-flow" |
	"-webkit-flex-grow" |
	"-webkit-flex-shrink" |
	"-webkit-flex-wrap" |
	"-webkit-justify-content" |
	"-webkit-order" |
	"-webkit-perspective" |
	"-webkit-perspective-origin" |
	"-webkit-tap-highlight-color" |
	"-webkit-text-fill-color" |
	"-webkit-text-size-adjust" |
	"-webkit-text-stroke" |
	"-webkit-text-stroke-color" |
	"-webkit-text-stroke-width" |
	"-webkit-transform" |
	"-webkit-transform-origin" |
	"-webkit-transform-style" |
	"-webkit-transition" |
	"-webkit-transition-delay" |
	"-webkit-transition-duration" |
	"-webkit-transition-property" |
	"-webkit-transition-timing-function" |
	"-webkit-user-modify" |
	"-webkit-user-select" |
	"-webkit-writing-mode" |
	"white-space" |
	"widows" |
	"width" |
	"word-break" |
	"word-spacing" |
	"word-wrap" |
	"writing-mode" |
	"z-index" |
	"zoom" |
	"resize" |
	"user-select";
