export type Pseudo = ":before" |
	"::before" |
	":after" |
	"::after" |
	":blank" |
	":checked" |
	":default" |
	":disabled" |
	":empty" |
	":enabled" |
	"::first-letter" |
	"::first-line" |
	":first-child" |
	":first-of-type" |
	":focus" |
	":hover" |
	":in-range" |
	":indeterminate" |
	":invalid" |
	":last-child" |
	":last-of-type" |
	":link" |
	"::marker" |
	":nth-child" |
	":nth-last-child" |
	":nth-of-type" |
	":only-child" |
	":only-of-type" |
	":optional" |
	":out-of-range" |
	"::placeholder" |
	":placeholder-shown" |
	":read-write" |
	":read-only" |
	":required" |
	":root" |
	"::selection" |
	":target" |
	":user-invalid" |
	":valid" |
	":visited" |
	string;
