import CSSNumber from "../CSSNumber";

// Note: these things are inlined because auto-completion likes it that way

export type StyleObject = {
	// Pseudo-selectors
	":before"?: StyleObject;
	"::before"?: StyleObject;
	":after"?: StyleObject;
	"::after"?: StyleObject;
	":blank"?: StyleObject;
	":checked"?: StyleObject;
	":default"?: StyleObject;
	":disabled"?: StyleObject;
	":empty"?: StyleObject;
	":enabled"?: StyleObject;
	"::first-letter"?: StyleObject;
	"::first-line"?: StyleObject;
	":first-child"?: StyleObject;
	":first-of-type"?: StyleObject;
	":focus"?: StyleObject;
	":hover"?: StyleObject;
	":in-range"?: StyleObject;
	":indeterminate"?: StyleObject;
	":invalid"?: StyleObject;
	":last-child"?: StyleObject;
	":last-of-type"?: StyleObject;
	":link"?: StyleObject;
	"::marker"?: StyleObject;
	":nth-child"?: StyleObject;
	":nth-last-child"?: StyleObject;
	":nth-of-type"?: StyleObject;
	":only-child"?: StyleObject;
	":only-of-type"?: StyleObject;
	":optional"?: StyleObject;
	":out-of-range"?: StyleObject;
	"::placeholder"?: StyleObject;
	":placeholder-shown"?: StyleObject;
	":read-write"?: StyleObject;
	":read-only"?: StyleObject;
	":required"?: StyleObject;
	":root"?: StyleObject;
	"::selection"?: StyleObject;
	":target"?: StyleObject;
	":user-invalid"?: StyleObject;
	":valid"?: StyleObject;
	":visited"?: StyleObject;

	// Properties
	"alignContent"?: string | CSSNumber;
	"alignItems"?: string | CSSNumber;
	"alignSelf"?: string | CSSNumber;
	"alignmentBaseline"?: string | CSSNumber;
	"animation"?: string | CSSNumber;
	"animationDelay"?: string | CSSNumber;
	"animationDirection"?: string | CSSNumber;
	"animationDuration"?: string | CSSNumber;
	"animationFillMode"?: string | CSSNumber;
	"animationIterationCount"?: string | CSSNumber;
	"animationName"?: string | CSSNumber;
	"animationPlayState"?: string | CSSNumber;
	"animationTimingFunction"?: string | CSSNumber;
	"backfaceVisibility"?: string | CSSNumber;
	"background"?: string | CSSNumber;
	"backgroundAttachment"?: string | CSSNumber;
	"backgroundClip"?: string | CSSNumber;
	"backgroundColor"?: string | CSSNumber;
	"backgroundImage"?: string | CSSNumber;
	"backgroundOrigin"?: string | CSSNumber;
	"backgroundPosition"?: string | CSSNumber;
	"backgroundPositionX"?: string | CSSNumber;
	"backgroundPositionY"?: string | CSSNumber;
	"backgroundRepeat"?: string | CSSNumber;
	"backgroundSize"?: string | CSSNumber;
	"baselineShift"?: string | CSSNumber;
	"border"?: string | CSSNumber;
	"borderBottom"?: string | CSSNumber;
	"borderBottomColor"?: string | CSSNumber;
	"borderBottomLeftRadius"?: string | CSSNumber;
	"borderBottomRightRadius"?: string | CSSNumber;
	"borderBottomStyle"?: string | CSSNumber;
	"borderBottomWidth"?: string | CSSNumber;
	"borderCollapse"?: string | CSSNumber;
	"borderColor"?: string | CSSNumber;
	"borderImage"?: string | CSSNumber;
	"borderImageOutset"?: string | CSSNumber;
	"borderImageRepeat"?: string | CSSNumber;
	"borderImageSlice"?: string | CSSNumber;
	"borderImageSource"?: string | CSSNumber;
	"borderImageWidth"?: string | CSSNumber;
	"borderLeft"?: string | CSSNumber;
	"borderLeftColor"?: string | CSSNumber;
	"borderLeftStyle"?: string | CSSNumber;
	"borderLeftWidth"?: string | CSSNumber;
	"borderRadius"?: string | CSSNumber;
	"borderRight"?: string | CSSNumber;
	"borderRightColor"?: string | CSSNumber;
	"borderRightStyle"?: string | CSSNumber;
	"borderRightWidth"?: string | CSSNumber;
	"borderSpacing"?: string | CSSNumber;
	"borderStyle"?: string | CSSNumber;
	"borderTop"?: string | CSSNumber;
	"borderTopColor"?: string | CSSNumber;
	"borderTopLeftRadius"?: string | CSSNumber;
	"borderTopRightRadius"?: string | CSSNumber;
	"borderTopStyle"?: string | CSSNumber;
	"borderTopWidth"?: string | CSSNumber;
	"borderWidth"?: string | CSSNumber;
	"bottom"?: string | CSSNumber;
	"boxShadow"?: string | CSSNumber;
	"boxSizing"?: string | CSSNumber;
	"breakAfter"?: string | CSSNumber;
	"breakBefore"?: string | CSSNumber;
	"breakInside"?: string | CSSNumber;
	"captionSide"?: string | CSSNumber;
	"clear"?: string | CSSNumber;
	"clip"?: string | CSSNumber;
	"clipPath"?: string | CSSNumber;
	"clipRule"?: string | CSSNumber;
	"color"?: string | CSSNumber;
	"colorInterpolationFilters"?: string | CSSNumber;
	"columnCount"?: string | CSSNumber;
	"columnFill"?: string | CSSNumber;
	"columnGap"?: string | CSSNumber;
	"columnRule"?: string | CSSNumber;
	"columnRuleColor"?: string | CSSNumber;
	"columnRuleStyle"?: string | CSSNumber;
	"columnRuleWidth"?: string | CSSNumber;
	"columnSpan"?: string | CSSNumber;
	"columnWidth"?: string | CSSNumber;
	"columns"?: string | CSSNumber;
	"content"?: string | CSSNumber;
	"counterIncrement"?: string | CSSNumber;
	"counterReset"?: string | CSSNumber;
	"cssFloat"?: string | CSSNumber;
	"cssText"?: string | CSSNumber;
	"cursor"?: string | CSSNumber;
	"direction"?: string | CSSNumber;
	"display"?: string | CSSNumber;
	"dominantBaseline"?: string | CSSNumber;
	"emptyCells"?: string | CSSNumber;
	"enableBackground"?: string | CSSNumber;
	"fill"?: string | CSSNumber;
	"fillOpacity"?: string | CSSNumber;
	"fillRule"?: string | CSSNumber;
	"filter"?: string | CSSNumber;
	"flex"?: string | CSSNumber;
	"flexBasis"?: string | CSSNumber;
	"flexDirection"?: string | CSSNumber;
	"flexFlow"?: string | CSSNumber;
	"flexGrow"?: string | CSSNumber;
	"flexShrink"?: string | CSSNumber;
	"flexWrap"?: string | CSSNumber;
	"floodColor"?: string | CSSNumber;
	"floodOpacity"?: string | CSSNumber;
	"font"?: string | CSSNumber;
	"fontFamily"?: string | CSSNumber;
	"fontFeatureSettings"?: string | CSSNumber;
	"fontSize"?: string | CSSNumber;
	"fontSizeAdjust"?: string | CSSNumber;
	"fontStretch"?: string | CSSNumber;
	"fontStyle"?: string | CSSNumber;
	"fontVariant"?: string | CSSNumber;
	"fontWeight"?: string | CSSNumber;
	"glyphOrientationHorizontal"?: string | CSSNumber;
	"glyphOrientationVertical"?: string | CSSNumber;
	"height"?: string | CSSNumber;
	"imeMode"?: string | CSSNumber;
	"justifyContent"?: string | CSSNumber;
	"kerning"?: string | CSSNumber;
	"layoutGrid"?: string | CSSNumber;
	"layoutGridChar"?: string | CSSNumber;
	"layoutGridLine"?: string | CSSNumber;
	"layoutGridMode"?: string | CSSNumber;
	"layoutGridType"?: string | CSSNumber;
	"left"?: string | CSSNumber;
	"letterSpacing"?: string | CSSNumber;
	"lightingColor"?: string | CSSNumber;
	"lineBreak"?: string | CSSNumber;
	"lineHeight"?: string | CSSNumber;
	"listStyle"?: string | CSSNumber;
	"listStyleImage"?: string | CSSNumber;
	"listStylePosition"?: string | CSSNumber;
	"listStyleType"?: string | CSSNumber;
	"margin"?: string | CSSNumber;
	"marginBottom"?: string | CSSNumber;
	"marginLeft"?: string | CSSNumber;
	"marginRight"?: string | CSSNumber;
	"marginTop"?: string | CSSNumber;
	"marker"?: string | CSSNumber;
	"markerEnd"?: string | CSSNumber;
	"markerMid"?: string | CSSNumber;
	"markerStart"?: string | CSSNumber;
	"mask"?: string | CSSNumber;
	"maxHeight"?: string | CSSNumber;
	"maxWidth"?: string | CSSNumber;
	"minHeight"?: string | CSSNumber;
	"minWidth"?: string | CSSNumber;
	"msContentZoomChaining"?: string | CSSNumber;
	"msContentZoomLimit"?: string | CSSNumber;
	"msContentZoomLimitMax"?: string | CSSNumber;
	"msContentZoomLimitMin"?: string | CSSNumber;
	"msContentZoomSnap"?: string | CSSNumber;
	"msContentZoomSnapPoints"?: string | CSSNumber;
	"msContentZoomSnapType"?: string | CSSNumber;
	"msContentZooming"?: string | CSSNumber;
	"msFlowFrom"?: string | CSSNumber;
	"msFlowInto"?: string | CSSNumber;
	"msFontFeatureSettings"?: string | CSSNumber;
	"msGridColumn"?: string | CSSNumber;
	"msGridColumnAlign"?: string | CSSNumber;
	"msGridColumnSpan"?: string | CSSNumber;
	"msGridColumns"?: string | CSSNumber;
	"msGridRow"?: string | CSSNumber;
	"msGridRowAlign"?: string | CSSNumber;
	"msGridRowSpan"?: string | CSSNumber;
	"msGridRows"?: string | CSSNumber;
	"msHighContrastAdjust"?: string | CSSNumber;
	"msHyphenateLimitChars"?: string | CSSNumber;
	"msHyphenateLimitLines"?: string | CSSNumber;
	"msHyphenateLimitZone"?: string | CSSNumber;
	"msHyphens"?: string | CSSNumber;
	"msImeAlign"?: string | CSSNumber;
	"msOverflowStyle"?: string | CSSNumber;
	"msScrollChaining"?: string | CSSNumber;
	"msScrollLimit"?: string | CSSNumber;
	"msScrollLimitXMax"?: string | CSSNumber;
	"msScrollLimitXMin"?: string | CSSNumber;
	"msScrollLimitYMax"?: string | CSSNumber;
	"msScrollLimitYMin"?: string | CSSNumber;
	"msScrollRails"?: string | CSSNumber;
	"msScrollSnapPointsX"?: string | CSSNumber;
	"msScrollSnapPointsY"?: string | CSSNumber;
	"msScrollSnapType"?: string | CSSNumber;
	"msScrollSnapX"?: string | CSSNumber;
	"msScrollSnapY"?: string | CSSNumber;
	"msScrollTranslation"?: string | CSSNumber;
	"msTextCombineHorizontal"?: string | CSSNumber;
	"msTextSizeAdjust"?: string | CSSNumber;
	"msTouchAction"?: string | CSSNumber;
	"msTouchSelect"?: string | CSSNumber;
	"msUserSelect"?: string | CSSNumber;
	"msWrapFlow"?: string | CSSNumber;
	"msWrapMargin"?: string | CSSNumber;
	"msWrapThrough"?: string | CSSNumber;
	"opacity"?: string | CSSNumber;
	"order"?: string | CSSNumber;
	"orphans"?: string | CSSNumber;
	"outline"?: string | CSSNumber;
	"outlineColor"?: string | CSSNumber;
	"outlineOffset"?: string | CSSNumber;
	"outlineStyle"?: string | CSSNumber;
	"outlineWidth"?: string | CSSNumber;
	"overflow"?: string | CSSNumber;
	"overflowX"?: string | CSSNumber;
	"overflowY"?: string | CSSNumber;
	"padding"?: string | CSSNumber;
	"paddingBottom"?: string | CSSNumber;
	"paddingLeft"?: string | CSSNumber;
	"paddingRight"?: string | CSSNumber;
	"paddingTop"?: string | CSSNumber;
	"pageBreakAfter"?: string | CSSNumber;
	"pageBreakBefore"?: string | CSSNumber;
	"pageBreakInside"?: string | CSSNumber;
	"readonly"?: string | CSSNumber;
	"perspective"?: string | CSSNumber;
	"perspectiveOrigin"?: string | CSSNumber;
	"pointerEvents"?: string | CSSNumber;
	"position"?: string | CSSNumber;
	"quotes"?: string | CSSNumber;
	"right"?: string | CSSNumber;
	"rotate"?: string | CSSNumber;
	"rubyAlign"?: string | CSSNumber;
	"rubyOverhang"?: string | CSSNumber;
	"rubyPosition"?: string | CSSNumber;
	"scale"?: string | CSSNumber;
	"stopColor"?: string | CSSNumber;
	"stopOpacity"?: string | CSSNumber;
	"stroke"?: string | CSSNumber;
	"strokeDasharray"?: string | CSSNumber;
	"strokeDashoffset"?: string | CSSNumber;
	"strokeLinecap"?: string | CSSNumber;
	"strokeLinejoin"?: string | CSSNumber;
	"strokeMiterlimit"?: string | CSSNumber;
	"strokeOpacity"?: string | CSSNumber;
	"strokeWidth"?: string | CSSNumber;
	"tableLayout"?: string | CSSNumber;
	"textAlign"?: string | CSSNumber;
	"textAlignLast"?: string | CSSNumber;
	"textAnchor"?: string | CSSNumber;
	"textDecoration"?: string | CSSNumber;
	"textIndent"?: string | CSSNumber;
	"textJustify"?: string | CSSNumber;
	"textKashida"?: string | CSSNumber;
	"textKashidaSpace"?: string | CSSNumber;
	"textOverflow"?: string | CSSNumber;
	"textShadow"?: string | CSSNumber;
	"textTransform"?: string | CSSNumber;
	"textUnderlinePosition"?: string | CSSNumber;
	"top"?: string | CSSNumber;
	"touchAction"?: string | CSSNumber;
	"transform"?: string | CSSNumber;
	"transformOrigin"?: string | CSSNumber;
	"transformStyle"?: string | CSSNumber;
	"transition"?: string | CSSNumber;
	"transitionDelay"?: string | CSSNumber;
	"transitionDuration"?: string | CSSNumber;
	"transitionProperty"?: string | CSSNumber;
	"transitionTimingFunction"?: string | CSSNumber;
	"translate"?: string | CSSNumber;
	"unicodeBidi"?: string | CSSNumber;
	"verticalAlign"?: string | CSSNumber;
	"visibility"?: string | CSSNumber;
	"webkitAlignContent"?: string | CSSNumber;
	"webkitAlignItems"?: string | CSSNumber;
	"webkitAlignSelf"?: string | CSSNumber;
	"webkitAnimation"?: string | CSSNumber;
	"webkitAnimationDelay"?: string | CSSNumber;
	"webkitAnimationDirection"?: string | CSSNumber;
	"webkitAnimationDuration"?: string | CSSNumber;
	"webkitAnimationFillMode"?: string | CSSNumber;
	"webkitAnimationIterationCount"?: string | CSSNumber;
	"webkitAnimationName"?: string | CSSNumber;
	"webkitAnimationPlayState"?: string | CSSNumber;
	"webkitAnimationTimingFunction"?: string | CSSNumber;
	"webkitAppearance"?: string | CSSNumber;
	"webkitBackfaceVisibility"?: string | CSSNumber;
	"webkitBackgroundClip"?: string | CSSNumber;
	"webkitBackgroundOrigin"?: string | CSSNumber;
	"webkitBackgroundSize"?: string | CSSNumber;
	"webkitBorderBottomLeftRadius"?: string | CSSNumber;
	"webkitBorderBottomRightRadius"?: string | CSSNumber;
	"webkitBorderImage"?: string | CSSNumber;
	"webkitBorderRadius"?: string | CSSNumber;
	"webkitBorderTopLeftRadius"?: string | CSSNumber;
	"webkitBorderTopRightRadius"?: string | CSSNumber;
	"webkitBoxAlign"?: string | CSSNumber;
	"webkitBoxDirection"?: string | CSSNumber;
	"webkitBoxFlex"?: string | CSSNumber;
	"webkitBoxOrdinalGroup"?: string | CSSNumber;
	"webkitBoxOrient"?: string | CSSNumber;
	"webkitBoxPack"?: string | CSSNumber;
	"webkitBoxSizing"?: string | CSSNumber;
	"webkitColumnBreakAfter"?: string | CSSNumber;
	"webkitColumnBreakBefore"?: string | CSSNumber;
	"webkitColumnBreakInside"?: string | CSSNumber;
	"webkitColumnCount"?: string | CSSNumber;
	"webkitColumnGap"?: string | CSSNumber;
	"webkitColumnRule"?: string | CSSNumber;
	"webkitColumnRuleColor"?: string | CSSNumber;
	"webkitColumnRuleStyle"?: string | CSSNumber;
	"webkitColumnRuleWidth"?: string | CSSNumber;
	"webkitColumnSpan"?: string | CSSNumber;
	"webkitColumnWidth"?: string | CSSNumber;
	"webkitColumns"?: string | CSSNumber;
	"webkitFilter"?: string | CSSNumber;
	"webkitFlex"?: string | CSSNumber;
	"webkitFlexBasis"?: string | CSSNumber;
	"webkitFlexDirection"?: string | CSSNumber;
	"webkitFlexFlow"?: string | CSSNumber;
	"webkitFlexGrow"?: string | CSSNumber;
	"webkitFlexShrink"?: string | CSSNumber;
	"webkitFlexWrap"?: string | CSSNumber;
	"webkitJustifyContent"?: string | CSSNumber;
	"webkitOrder"?: string | CSSNumber;
	"webkitPerspective"?: string | CSSNumber;
	"webkitPerspectiveOrigin"?: string | CSSNumber;
	"webkitTapHighlightColor"?: string | CSSNumber;
	"webkitTextFillColor"?: string | CSSNumber;
	"webkitTextSizeAdjust"?: string | CSSNumber;
	"webkitTextStroke"?: string | CSSNumber;
	"webkitTextStrokeColor"?: string | CSSNumber;
	"webkitTextStrokeWidth"?: string | CSSNumber;
	"webkitTransform"?: string | CSSNumber;
	"webkitTransformOrigin"?: string | CSSNumber;
	"webkitTransformStyle"?: string | CSSNumber;
	"webkitTransition"?: string | CSSNumber;
	"webkitTransitionDelay"?: string | CSSNumber;
	"webkitTransitionDuration"?: string | CSSNumber;
	"webkitTransitionProperty"?: string | CSSNumber;
	"webkitTransitionTimingFunction"?: string | CSSNumber;
	"webkitUserModify"?: string | CSSNumber;
	"webkitUserSelect"?: string | CSSNumber;
	"webkitWritingMode"?: string | CSSNumber;
	"whiteSpace"?: string | CSSNumber;
	"widows"?: string | CSSNumber;
	"width"?: string | CSSNumber;
	"wordBreak"?: string | CSSNumber;
	"wordSpacing"?: string | CSSNumber;
	"wordWrap"?: string | CSSNumber;
	"writingMode"?: string | CSSNumber;
	"zIndex"?: string | CSSNumber;
	"zoom"?: string | CSSNumber;
	"resize"?: string | CSSNumber;
	"userSelect"?: string | CSSNumber;

	[others: string]: string | CSSNumber | StyleObject;
};
