import CSSNumber from "../CSSNumber";

// Note: these things are inlined because auto-completion likes it that way

export type StyleObject = {
	// Pseudo-selectors
	":before"?: StyleObject;
	"::before"?: StyleObject;
	":after"?: StyleObject;
	"::after"?: StyleObject;
	":blank"?: StyleObject;
	":checked"?: StyleObject;
	":default"?: StyleObject;
	":disabled"?: StyleObject;
	":empty"?: StyleObject;
	":enabled"?: StyleObject;
	"::first-letter"?: StyleObject;
	"::first-line"?: StyleObject;
	":first-child"?: StyleObject;
	":first-of-type"?: StyleObject;
	":focus"?: StyleObject;
	":hover"?: StyleObject;
	":in-range"?: StyleObject;
	":indeterminate"?: StyleObject;
	":invalid"?: StyleObject;
	":last-child"?: StyleObject;
	":last-of-type"?: StyleObject;
	":link"?: StyleObject;
	"::marker"?: StyleObject;
	":nth-child"?: StyleObject;
	":nth-last-child"?: StyleObject;
	":nth-of-type"?: StyleObject;
	":only-child"?: StyleObject;
	":only-of-type"?: StyleObject;
	":optional"?: StyleObject;
	":out-of-range"?: StyleObject;
	"::placeholder"?: StyleObject;
	":placeholder-shown"?: StyleObject;
	":read-write"?: StyleObject;
	":read-only"?: StyleObject;
	":required"?: StyleObject;
	":root"?: StyleObject;
	"::selection"?: StyleObject;
	":target"?: StyleObject;
	":user-invalid"?: StyleObject;
	":valid"?: StyleObject;
	":visited"?: StyleObject;

	// Properties
	"alignContent"?: string | CSSNumber | number;
	"alignItems"?: string | CSSNumber | number;
	"alignSelf"?: string | CSSNumber | number;
	"alignmentBaseline"?: string | CSSNumber | number;
	"animation"?: string | CSSNumber | number;
	"animationDelay"?: string | CSSNumber | number;
	"animationDirection"?: string | CSSNumber | number;
	"animationDuration"?: string | CSSNumber | number;
	"animationFillMode"?: string | CSSNumber | number;
	"animationIterationCount"?: string | CSSNumber | number;
	"animationName"?: string | CSSNumber | number;
	"animationPlayState"?: string | CSSNumber | number;
	"animationTimingFunction"?: string | CSSNumber | number;
	"backfaceVisibility"?: string | CSSNumber | number;
	"background"?: string | CSSNumber | number;
	"backgroundAttachment"?: string | CSSNumber | number;
	"backgroundClip"?: string | CSSNumber | number;
	"backgroundColor"?: string | CSSNumber | number;
	"backgroundImage"?: string | CSSNumber | number;
	"backgroundOrigin"?: string | CSSNumber | number;
	"backgroundPosition"?: string | CSSNumber | number;
	"backgroundPositionX"?: string | CSSNumber | number;
	"backgroundPositionY"?: string | CSSNumber | number;
	"backgroundRepeat"?: string | CSSNumber | number;
	"backgroundSize"?: string | CSSNumber | number;
	"baselineShift"?: string | CSSNumber | number;
	"border"?: string | CSSNumber | number;
	"borderBottom"?: string | CSSNumber | number;
	"borderBottomColor"?: string | CSSNumber | number;
	"borderBottomLeftRadius"?: string | CSSNumber | number;
	"borderBottomRightRadius"?: string | CSSNumber | number;
	"borderBottomStyle"?: string | CSSNumber | number;
	"borderBottomWidth"?: string | CSSNumber | number;
	"borderCollapse"?: string | CSSNumber | number;
	"borderColor"?: string | CSSNumber | number;
	"borderImage"?: string | CSSNumber | number;
	"borderImageOutset"?: string | CSSNumber | number;
	"borderImageRepeat"?: string | CSSNumber | number;
	"borderImageSlice"?: string | CSSNumber | number;
	"borderImageSource"?: string | CSSNumber | number;
	"borderImageWidth"?: string | CSSNumber | number;
	"borderLeft"?: string | CSSNumber | number;
	"borderLeftColor"?: string | CSSNumber | number;
	"borderLeftStyle"?: string | CSSNumber | number;
	"borderLeftWidth"?: string | CSSNumber | number;
	"borderRadius"?: string | CSSNumber | number;
	"borderRight"?: string | CSSNumber | number;
	"borderRightColor"?: string | CSSNumber | number;
	"borderRightStyle"?: string | CSSNumber | number;
	"borderRightWidth"?: string | CSSNumber | number;
	"borderSpacing"?: string | CSSNumber | number;
	"borderStyle"?: string | CSSNumber | number;
	"borderTop"?: string | CSSNumber | number;
	"borderTopColor"?: string | CSSNumber | number;
	"borderTopLeftRadius"?: string | CSSNumber | number;
	"borderTopRightRadius"?: string | CSSNumber | number;
	"borderTopStyle"?: string | CSSNumber | number;
	"borderTopWidth"?: string | CSSNumber | number;
	"borderWidth"?: string | CSSNumber | number;
	"bottom"?: string | CSSNumber | number;
	"boxShadow"?: string | CSSNumber | number;
	"boxSizing"?: string | CSSNumber | number;
	"breakAfter"?: string | CSSNumber | number;
	"breakBefore"?: string | CSSNumber | number;
	"breakInside"?: string | CSSNumber | number;
	"captionSide"?: string | CSSNumber | number;
	"clear"?: string | CSSNumber | number;
	"clip"?: string | CSSNumber | number;
	"clipPath"?: string | CSSNumber | number;
	"clipRule"?: string | CSSNumber | number;
	"color"?: string | CSSNumber | number;
	"colorInterpolationFilters"?: string | CSSNumber | number;
	"columnCount"?: string | CSSNumber | number;
	"columnFill"?: string | CSSNumber | number;
	"columnGap"?: string | CSSNumber | number;
	"columnRule"?: string | CSSNumber | number;
	"columnRuleColor"?: string | CSSNumber | number;
	"columnRuleStyle"?: string | CSSNumber | number;
	"columnRuleWidth"?: string | CSSNumber | number;
	"columnSpan"?: string | CSSNumber | number;
	"columnWidth"?: string | CSSNumber | number;
	"columns"?: string | CSSNumber | number;
	"content"?: string | CSSNumber | number;
	"counterIncrement"?: string | CSSNumber | number;
	"counterReset"?: string | CSSNumber | number;
	"cssFloat"?: string | CSSNumber | number;
	"cssText"?: string | CSSNumber | number;
	"cursor"?: string | CSSNumber | number;
	"direction"?: string | CSSNumber | number;
	"display"?: string | CSSNumber | number;
	"dominantBaseline"?: string | CSSNumber | number;
	"emptyCells"?: string | CSSNumber | number;
	"enableBackground"?: string | CSSNumber | number;
	"fill"?: string | CSSNumber | number;
	"fillOpacity"?: string | CSSNumber | number;
	"fillRule"?: string | CSSNumber | number;
	"filter"?: string | CSSNumber | number;
	"flex"?: string | CSSNumber | number;
	"flexBasis"?: string | CSSNumber | number;
	"flexDirection"?: string | CSSNumber | number;
	"flexFlow"?: string | CSSNumber | number;
	"flexGrow"?: string | CSSNumber | number;
	"flexShrink"?: string | CSSNumber | number;
	"flexWrap"?: string | CSSNumber | number;
	"floodColor"?: string | CSSNumber | number;
	"floodOpacity"?: string | CSSNumber | number;
	"font"?: string | CSSNumber | number;
	"fontFamily"?: string | CSSNumber | number;
	"fontFeatureSettings"?: string | CSSNumber | number;
	"fontSize"?: string | CSSNumber | number;
	"fontSizeAdjust"?: string | CSSNumber | number;
	"fontStretch"?: string | CSSNumber | number;
	"fontStyle"?: string | CSSNumber | number;
	"fontVariant"?: string | CSSNumber | number;
	"fontWeight"?: string | CSSNumber | number;
	"glyphOrientationHorizontal"?: string | CSSNumber | number;
	"glyphOrientationVertical"?: string | CSSNumber | number;
	"height"?: string | CSSNumber | number;
	"imeMode"?: string | CSSNumber | number;
	"justifyContent"?: string | CSSNumber | number;
	"kerning"?: string | CSSNumber | number;
	"layoutGrid"?: string | CSSNumber | number;
	"layoutGridChar"?: string | CSSNumber | number;
	"layoutGridLine"?: string | CSSNumber | number;
	"layoutGridMode"?: string | CSSNumber | number;
	"layoutGridType"?: string | CSSNumber | number;
	"left"?: string | CSSNumber | number;
	"letterSpacing"?: string | CSSNumber | number;
	"lightingColor"?: string | CSSNumber | number;
	"lineBreak"?: string | CSSNumber | number;
	"lineHeight"?: string | CSSNumber | number;
	"listStyle"?: string | CSSNumber | number;
	"listStyleImage"?: string | CSSNumber | number;
	"listStylePosition"?: string | CSSNumber | number;
	"listStyleType"?: string | CSSNumber | number;
	"margin"?: string | CSSNumber | number;
	"marginBottom"?: string | CSSNumber | number;
	"marginLeft"?: string | CSSNumber | number;
	"marginRight"?: string | CSSNumber | number;
	"marginTop"?: string | CSSNumber | number;
	"marker"?: string | CSSNumber | number;
	"markerEnd"?: string | CSSNumber | number;
	"markerMid"?: string | CSSNumber | number;
	"markerStart"?: string | CSSNumber | number;
	"mask"?: string | CSSNumber | number;
	"maxHeight"?: string | CSSNumber | number;
	"maxWidth"?: string | CSSNumber | number;
	"minHeight"?: string | CSSNumber | number;
	"minWidth"?: string | CSSNumber | number;
	"msContentZoomChaining"?: string | CSSNumber | number;
	"msContentZoomLimit"?: string | CSSNumber | number;
	"msContentZoomLimitMax"?: string | CSSNumber | number;
	"msContentZoomLimitMin"?: string | CSSNumber | number;
	"msContentZoomSnap"?: string | CSSNumber | number;
	"msContentZoomSnapPoints"?: string | CSSNumber | number;
	"msContentZoomSnapType"?: string | CSSNumber | number;
	"msContentZooming"?: string | CSSNumber | number;
	"msFlowFrom"?: string | CSSNumber | number;
	"msFlowInto"?: string | CSSNumber | number;
	"msFontFeatureSettings"?: string | CSSNumber | number;
	"msGridColumn"?: string | CSSNumber | number;
	"msGridColumnAlign"?: string | CSSNumber | number;
	"msGridColumnSpan"?: string | CSSNumber | number;
	"msGridColumns"?: string | CSSNumber | number;
	"msGridRow"?: string | CSSNumber | number;
	"msGridRowAlign"?: string | CSSNumber | number;
	"msGridRowSpan"?: string | CSSNumber | number;
	"msGridRows"?: string | CSSNumber | number;
	"msHighContrastAdjust"?: string | CSSNumber | number;
	"msHyphenateLimitChars"?: string | CSSNumber | number;
	"msHyphenateLimitLines"?: string | CSSNumber | number;
	"msHyphenateLimitZone"?: string | CSSNumber | number;
	"msHyphens"?: string | CSSNumber | number;
	"msImeAlign"?: string | CSSNumber | number;
	"msOverflowStyle"?: string | CSSNumber | number;
	"msScrollChaining"?: string | CSSNumber | number;
	"msScrollLimit"?: string | CSSNumber | number;
	"msScrollLimitXMax"?: string | CSSNumber | number;
	"msScrollLimitXMin"?: string | CSSNumber | number;
	"msScrollLimitYMax"?: string | CSSNumber | number;
	"msScrollLimitYMin"?: string | CSSNumber | number;
	"msScrollRails"?: string | CSSNumber | number;
	"msScrollSnapPointsX"?: string | CSSNumber | number;
	"msScrollSnapPointsY"?: string | CSSNumber | number;
	"msScrollSnapType"?: string | CSSNumber | number;
	"msScrollSnapX"?: string | CSSNumber | number;
	"msScrollSnapY"?: string | CSSNumber | number;
	"msScrollTranslation"?: string | CSSNumber | number;
	"msTextCombineHorizontal"?: string | CSSNumber | number;
	"msTextSizeAdjust"?: string | CSSNumber | number;
	"msTouchAction"?: string | CSSNumber | number;
	"msTouchSelect"?: string | CSSNumber | number;
	"msUserSelect"?: string | CSSNumber | number;
	"msWrapFlow"?: string | CSSNumber | number;
	"msWrapMargin"?: string | CSSNumber | number;
	"msWrapThrough"?: string | CSSNumber | number;
	"opacity"?: string | CSSNumber | number;
	"order"?: string | CSSNumber | number;
	"orphans"?: string | CSSNumber | number;
	"outline"?: string | CSSNumber | number;
	"outlineColor"?: string | CSSNumber | number;
	"outlineOffset"?: string | CSSNumber | number;
	"outlineStyle"?: string | CSSNumber | number;
	"outlineWidth"?: string | CSSNumber | number;
	"overflow"?: string | CSSNumber | number;
	"overflowX"?: string | CSSNumber | number;
	"overflowY"?: string | CSSNumber | number;
	"padding"?: string | CSSNumber | number;
	"paddingBottom"?: string | CSSNumber | number;
	"paddingLeft"?: string | CSSNumber | number;
	"paddingRight"?: string | CSSNumber | number;
	"paddingTop"?: string | CSSNumber | number;
	"pageBreakAfter"?: string | CSSNumber | number;
	"pageBreakBefore"?: string | CSSNumber | number;
	"pageBreakInside"?: string | CSSNumber | number;
	"readonly"?: string | CSSNumber | number;
	"perspective"?: string | CSSNumber | number;
	"perspectiveOrigin"?: string | CSSNumber | number;
	"pointerEvents"?: string | CSSNumber | number;
	"position"?: string | CSSNumber | number;
	"quotes"?: string | CSSNumber | number;
	"right"?: string | CSSNumber | number;
	"rotate"?: string | CSSNumber | number;
	"rubyAlign"?: string | CSSNumber | number;
	"rubyOverhang"?: string | CSSNumber | number;
	"rubyPosition"?: string | CSSNumber | number;
	"scale"?: string | CSSNumber | number;
	"stopColor"?: string | CSSNumber | number;
	"stopOpacity"?: string | CSSNumber | number;
	"stroke"?: string | CSSNumber | number;
	"strokeDasharray"?: string | CSSNumber | number;
	"strokeDashoffset"?: string | CSSNumber | number;
	"strokeLinecap"?: string | CSSNumber | number;
	"strokeLinejoin"?: string | CSSNumber | number;
	"strokeMiterlimit"?: string | CSSNumber | number;
	"strokeOpacity"?: string | CSSNumber | number;
	"strokeWidth"?: string | CSSNumber | number;
	"tableLayout"?: string | CSSNumber | number;
	"textAlign"?: string | CSSNumber | number;
	"textAlignLast"?: string | CSSNumber | number;
	"textAnchor"?: string | CSSNumber | number;
	"textDecoration"?: string | CSSNumber | number;
	"textIndent"?: string | CSSNumber | number;
	"textJustify"?: string | CSSNumber | number;
	"textKashida"?: string | CSSNumber | number;
	"textKashidaSpace"?: string | CSSNumber | number;
	"textOverflow"?: string | CSSNumber | number;
	"textShadow"?: string | CSSNumber | number;
	"textTransform"?: string | CSSNumber | number;
	"textUnderlinePosition"?: string | CSSNumber | number;
	"top"?: string | CSSNumber | number;
	"touchAction"?: string | CSSNumber | number;
	"transform"?: string | CSSNumber | number;
	"transformOrigin"?: string | CSSNumber | number;
	"transformStyle"?: string | CSSNumber | number;
	"transition"?: string | CSSNumber | number;
	"transitionDelay"?: string | CSSNumber | number;
	"transitionDuration"?: string | CSSNumber | number;
	"transitionProperty"?: string | CSSNumber | number;
	"transitionTimingFunction"?: string | CSSNumber | number;
	"translate"?: string | CSSNumber | number;
	"unicodeBidi"?: string | CSSNumber | number;
	"verticalAlign"?: string | CSSNumber | number;
	"visibility"?: string | CSSNumber | number;
	"WebkitAlignContent"?: string | CSSNumber | number;
	"WebkitAlignItems"?: string | CSSNumber | number;
	"WebkitAlignSelf"?: string | CSSNumber | number;
	"WebkitAnimation"?: string | CSSNumber | number;
	"WebkitAnimationDelay"?: string | CSSNumber | number;
	"WebkitAnimationDirection"?: string | CSSNumber | number;
	"WebkitAnimationDuration"?: string | CSSNumber | number;
	"WebkitAnimationFillMode"?: string | CSSNumber | number;
	"WebkitAnimationIterationCount"?: string | CSSNumber | number;
	"WebkitAnimationName"?: string | CSSNumber | number;
	"WebkitAnimationPlayState"?: string | CSSNumber | number;
	"WebkitAnimationTimingFunction"?: string | CSSNumber | number;
	"WebkitAppearance"?: string | CSSNumber | number;
	"WebkitBackfaceVisibility"?: string | CSSNumber | number;
	"WebkitBackgroundClip"?: string | CSSNumber | number;
	"WebkitBackgroundOrigin"?: string | CSSNumber | number;
	"WebkitBackgroundSize"?: string | CSSNumber | number;
	"WebkitBorderBottomLeftRadius"?: string | CSSNumber | number;
	"WebkitBorderBottomRightRadius"?: string | CSSNumber | number;
	"WebkitBorderImage"?: string | CSSNumber | number;
	"WebkitBorderRadius"?: string | CSSNumber | number;
	"WebkitBorderTopLeftRadius"?: string | CSSNumber | number;
	"WebkitBorderTopRightRadius"?: string | CSSNumber | number;
	"WebkitBoxAlign"?: string | CSSNumber | number;
	"WebkitBoxDirection"?: string | CSSNumber | number;
	"WebkitBoxFlex"?: string | CSSNumber | number;
	"WebkitBoxOrdinalGroup"?: string | CSSNumber | number;
	"WebkitBoxOrient"?: string | CSSNumber | number;
	"WebkitBoxPack"?: string | CSSNumber | number;
	"WebkitBoxSizing"?: string | CSSNumber | number;
	"WebkitColumnBreakAfter"?: string | CSSNumber | number;
	"WebkitColumnBreakBefore"?: string | CSSNumber | number;
	"WebkitColumnBreakInside"?: string | CSSNumber | number;
	"WebkitColumnCount"?: string | CSSNumber | number;
	"WebkitColumnGap"?: string | CSSNumber | number;
	"WebkitColumnRule"?: string | CSSNumber | number;
	"WebkitColumnRuleColor"?: string | CSSNumber | number;
	"WebkitColumnRuleStyle"?: string | CSSNumber | number;
	"WebkitColumnRuleWidth"?: string | CSSNumber | number;
	"WebkitColumnSpan"?: string | CSSNumber | number;
	"WebkitColumnWidth"?: string | CSSNumber | number;
	"WebkitColumns"?: string | CSSNumber | number;
	"WebkitFilter"?: string | CSSNumber | number;
	"WebkitFlex"?: string | CSSNumber | number;
	"WebkitFlexBasis"?: string | CSSNumber | number;
	"WebkitFlexDirection"?: string | CSSNumber | number;
	"WebkitFlexFlow"?: string | CSSNumber | number;
	"WebkitFlexGrow"?: string | CSSNumber | number;
	"WebkitFlexShrink"?: string | CSSNumber | number;
	"WebkitFlexWrap"?: string | CSSNumber | number;
	"WebkitJustifyContent"?: string | CSSNumber | number;
	"WebkitOrder"?: string | CSSNumber | number;
	"WebkitPerspective"?: string | CSSNumber | number;
	"WebkitPerspectiveOrigin"?: string | CSSNumber | number;
	"WebkitTapHighlightColor"?: string | CSSNumber | number;
	"WebkitTextFillColor"?: string | CSSNumber | number;
	"WebkitTextSizeAdjust"?: string | CSSNumber | number;
	"WebkitTextStroke"?: string | CSSNumber | number;
	"WebkitTextStrokeColor"?: string | CSSNumber | number;
	"WebkitTextStrokeWidth"?: string | CSSNumber | number;
	"WebkitTransform"?: string | CSSNumber | number;
	"WebkitTransformOrigin"?: string | CSSNumber | number;
	"WebkitTransformStyle"?: string | CSSNumber | number;
	"WebkitTransition"?: string | CSSNumber | number;
	"WebkitTransitionDelay"?: string | CSSNumber | number;
	"WebkitTransitionDuration"?: string | CSSNumber | number;
	"WebkitTransitionProperty"?: string | CSSNumber | number;
	"WebkitTransitionTimingFunction"?: string | CSSNumber | number;
	"WebkitUserModify"?: string | CSSNumber | number;
	"WebkitUserSelect"?: string | CSSNumber | number;
	"WebkitWritingMode"?: string | CSSNumber | number;
	"whiteSpace"?: string | CSSNumber | number;
	"widows"?: string | CSSNumber | number;
	"width"?: string | CSSNumber | number;
	"wordBreak"?: string | CSSNumber | number;
	"wordSpacing"?: string | CSSNumber | number;
	"wordWrap"?: string | CSSNumber | number;
	"writingMode"?: string | CSSNumber | number;
	"zIndex"?: string | CSSNumber | number;
	"zoom"?: string | CSSNumber | number;
	"resize"?: string | CSSNumber | number;
	"userSelect"?: string | CSSNumber | number;

	[others: string]: string | CSSNumber | number | StyleObject;
};
